/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RPSContract } from "./RPSContract";
export * as factories from "./factories";
export { RPSContract__factory } from "./factories/RPSContract__factory";
