/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export interface RPSPlayerContractInterface extends utils.Interface {
  functions: {
    "getCommitment()": FunctionFragment;
    "makeCommitment()": FunctionFragment;
    "provideRPSContractAddress(address)": FunctionFragment;
    "reveal()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getCommitment"
      | "makeCommitment"
      | "provideRPSContractAddress"
      | "reveal"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "makeCommitment",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "provideRPSContractAddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "reveal", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "getCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "makeCommitment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "provideRPSContractAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reveal", data: BytesLike): Result;

  events: {};
}

export interface RPSPlayerContract extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: RPSPlayerContractInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getCommitment(overrides?: CallOverrides): Promise<[string]>;

    makeCommitment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    provideRPSContractAddress(
      rps: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reveal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getCommitment(overrides?: CallOverrides): Promise<string>;

  makeCommitment(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  provideRPSContractAddress(
    rps: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reveal(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getCommitment(overrides?: CallOverrides): Promise<string>;

    makeCommitment(overrides?: CallOverrides): Promise<void>;

    provideRPSContractAddress(
      rps: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    reveal(overrides?: CallOverrides): Promise<void>;
  };

  filters: {};

  estimateGas: {
    getCommitment(overrides?: CallOverrides): Promise<BigNumber>;

    makeCommitment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    provideRPSContractAddress(
      rps: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reveal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getCommitment(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    makeCommitment(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    provideRPSContractAddress(
      rps: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reveal(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
